### ISSUE TITLE
TO-DO list to release

### ISSUE THREAD

**Issue by gamelaster** [arogan-group/irc4osu#1]
This is TO-DO list to a 1.0.0 version, I grab things from features part in README. I will update this with changes!
- [x] Simple design which fits new osu! design. (I mean if its whole coded)
- [x] Online users in current channel
- [x] Mouse hover player info
- [x] Notification sounds (when someone mentions you in the chat)
- [x] Simple channel management
- [x] Log in / Log out screen
- [ ] Beatmap management
- [x] Clean chat
- [ ] Online time
- [x] Auto-Update system
- [x] Windows, Linux, OS X Support (solved by Electron :P )

**Comment by gamelaster** [comment]
Really old, closing
